### ISSUE TITLE
在使用时报错

### ISSUE THREAD

**Issue by Cherryluoying** [XTxiaoting14332/nonebot-plugin-chatglm-plus#5]
06-19 22:38:13 [ERROR] nonebot | Running Matcher(type='message', module=nonebot_plugin_chatglm_plus, lineno=175) failed.
Traceback (most recent call last):
  File "<string>", line 15, in <module>
  File "C:\Users\Administrator\nbbot\.venv\lib\site-packages\nonebot\__init__.py", line 335, in run
    get_driver().run(*args, **kwargs)
  File "C:\Users\Administrator\nbbot\.venv\lib\site-packages\nonebot\drivers\fastapi.py", line 186, in run
    uvicorn.run(
  File "C:\Users\Administrator\nbbot\.venv\lib\site-packages\uvicorn\main.py", line 577, in run
    server.run()
  File "C:\Users\Administrator\nbbot\.venv\lib\site-packages\uvicorn\server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 633, in run_until_complete
    self.run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 600, in run_forever
    self._run_once()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1896, in _run_once
    handle._run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\Administrator\nbbot\.venv\lib\site-packages\nonebot\message.py", line 476, in check_and_run_matcher
    await _run_matcher(
> File "C:\Users\Administrator\nbbot\.venv\lib\site-packages\nonebot\message.py", line 428, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "C:\Users\Administrator\nbbot\.venv\lib\site-packages\nonebot\internal\matcher\matcher.py", line 850, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "C:\Users\Administrator\nbbot\.venv\lib\site-packages\nonebot\internal\matcher\matcher.py", line 825, in simple_run
    await handler(
  File "C:\Users\Administrator\nbbot\.venv\lib\site-packages\nonebot\dependencies\__init__.py", line 94, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "C:\Users\Administrator\nbbot\.venv\lib\site-packages\nonebot_plugin_chatglm_plus\__init__.py", line 333, in _handle
    ai_out(id,res_raw)
  File "C:\Users\Administrator\nbbot\.venv\lib\site-packages\nonebot_plugin_chatglm_plus\__init__.py", line 112, in ai_out
    file.write(',\n{"role": "assistant", "content": "' + text + '"}')
**UnicodeEncodeError: 'gbk' codec can't encode character '\U0001f319' in position 81: illegal multibyte sequence**

**Comment by Cherryluoying** [comment]
报错UnicodeEncodeError: 'gbk' codec can't encode character '\U0001f319' in position 81: illegal multibyte sequence

**Comment by XTxiaoting14332** [comment]
已修复，请将插件更新至 ``0.2.2`` 版本
